const mongoose = require("mongoose");

const orgSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, "Organization name is required"],
      trim: true,
      minlength: [2, "Name too short"],
      maxlength: [100, "Name too long"],
    },
    slug: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    plan: {
      type: String,
      enum: ["trial", "starter", "growth", "pro", "enterprise"],
      default: "trial",
    },
    trialEndsAt: {
      type: Date,
      default: () => new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // 14-day trial
    },
    isActive: { type: Boolean, default: true },
    industry:    { type: String, default: "Real Estate" },
    companySize: { type: String, default: "" },
    city:        { type: String, default: "" },
    onboardingCompletedAt: { type: Date, default: null },
    logo:       { type: String, default: "" },  // base64 data-URI or hosted URL
    brandColor: { type: String, default: "" },  // hex accent colour e.g. "#2563eb"
    autoAssign: { type: Boolean, default: true }, // round-robin auto-assign new leads to agents
    monthlyClosingGoal: { type: Number, default: 0, min: 0 },
    activeSupportSession: {
      active:          { type: Boolean, default: false },
      reason:          { type: String, default: "" },
      superAdminName:  { type: String, default: "" },
      startedAt:       { type: Date, default: null },
      requestId:       { type: mongoose.Schema.Types.ObjectId, default: null },
    },
    attendanceSettings: {
      shiftStartTime: { type: String, default: "09:30" }, // "HH:MM" 24-hour
      shiftEndTime:   { type: String, default: "19:00" }, // expected clock-out time
      bufferMinutes:  { type: Number, default: 15 },      // grace period before marked late
      halfDayMinutes: { type: Number, default: 240 },     // min minutes for half-day (4h)
      fullDayMinutes: { type: Number, default: 480 },     // min minutes for full-day (8h)
      requireSelfie:  { type: Boolean, default: true },   // require selfie on clock-in/out
    },
    // ── Billing / Invoice letterhead details ───────────────────────────────────
    address:         { type: String, default: "" },
    phone:           { type: String, default: "" },
    email:           { type: String, default: "" },
    gstNo:           { type: String, default: "" },
    pan:             { type: String, default: "" },
    cin:             { type: String, default: "" },
    rera:            { type: String, default: "" },
    bankAccountName: { type: String, default: "" },
    bankAccountNo:   { type: String, default: "" },
    bankIfsc:        { type: String, default: "" },
    bankName:        { type: String, default: "" },
    bankBranch:      { type: String, default: "" },

    // ── WhatsApp Integration ───────────────────────────────────────────────────
    whatsapp: {
      enabled:            { type: Boolean, default: false },
      provider:           { type: String, enum: ["aisensy", "wati", "interakt", "meta"], default: "aisensy" },
      apiKey:             { type: String, default: "" },   // API key / access token (all providers)
      accountEndpoint:    { type: String, default: "" },   // Wati: custom endpoint URL
      phoneNumberId:      { type: String, default: "" },   // Meta: phone number ID
      wabaId:             { type: String, default: "" },   // Meta: WABA ID
      webhookVerifyToken: { type: String, default: "" },   // Meta: webhook challenge token
      botEnabled:         { type: Boolean, default: true },
      botName:            { type: String, default: "Artha Assistant" },
      botSystemPrompt:    { type: String, default: "" },
    },

    // ── EnableX Telephony Integration ─────────────────────────────────────────
    enablex: {
      enabled:       { type: Boolean, default: false },
      appId:         { type: String,  default: "" },
      apiKey:        { type: String,  default: "" },  // APP KEY from EnableX dashboard
      virtualNumber: { type: String,  default: "" },  // virtual phone number to call from
      aiAutoStatus:  { type: Boolean, default: false }, // auto-advance lead status from AI intent
    },

    // ── Voice Integration API key (per-org, scoped to this tenant only) ─────────
    // Generated by admin via /api/org/voice-key; configured in the telephony provider.
    // Replacing the single global VOICE_API_KEY env var prevents one leaked key
    // from exposing all tenants.
    voiceApiKey:     { type: String, default: "", index: true, sparse: true },

    // ── QR Code lead capture ───────────────────────────────────────────────────
    qrToken:         { type: String, default: "", index: true, sparse: true },
    // ── Referral tracking ──────────────────────────────────────────────────────
    referralCode:    { type: String, uppercase: true, sparse: true, index: true },
    referredBy:      { type: mongoose.Schema.Types.ObjectId, ref: "Organization", default: null },
    referralRewardAt: { type: Date, default: null }, // set 7 days after referred org subscribes
  },
  { timestamps: true }
);

// Auto-generate referralCode from _id on first save
orgSchema.pre("save", function (next) {
  if (this.isNew && !this.referralCode) {
    this.referralCode = String(this._id).slice(-6).toUpperCase();
  }
  next();
});

// Generate slug from name
orgSchema.statics.generateSlug = function (name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50);
};

module.exports = mongoose.model("Organization", orgSchema);
